# Generated by Django 2.2.4 on 2020-05-01 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20200501_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_flat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='property.Flat', verbose_name='Квартира, на которую жаловались'),
        ),
    ]
