# Generated by Django 2.2.4 on 2020-05-02 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20200502_1516'),
        ('property', '0010_auto_20200502_1516'),
    ]

    operations = [
    ]
