# Generated by Django 2.2.4 on 2020-05-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owners_flats',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='flat_owned_by', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
