# Generated by Django 2.2.4 on 2020-05-02 18:00

from django.db import migrations


def data_transfer(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(
            name=flat.owner, phone_number=flat.owners_phonenumber, pure_phone_number=flat.owner_phone_pure)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20200502_2043'),
    ]

    operations = [
        migrations.RunPython(data_transfer)
    ]
