# Generated by Django 2.2.4 on 2020-05-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20200502_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owners',
            field=models.ManyToManyField(blank=True, db_index=True, to='property.Owner', verbose_name='Владельцы'),
        ),
    ]
