# Generated by Django 2.2.4 on 2020-05-02 18:20

from django.db import migrations


def transfer_owner_data(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for owner in Flat.objects.all():
        Owner.objects.get_or_create(owner=owner.owner,
                                    owners_phonenumber=owner.phone_number,
                                    owner_phone_pure=owner.pure_phone_number
                                    )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20200502_2100'),
    ]

    operations = [
        migrations.RunPython(transfer_owner_data)
    ]
