# Generated by Django 2.2.4 on 2020-05-02 18:20

from django.db import migrations


def transfer_owner_data(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all():
        flats_in_property = Flat.objects.filter(owner=owner.name)
        owner.owners_flats.set(flats_in_property)


def transfer_flat_data(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat_owners = flat.flat_owned_by.all()
        flat.owners.set(flat_owners)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20200502_2100'),
    ]

    operations = [
        migrations.RunPython(transfer_owner_data)
    ]
