# Generated by Django 2.2.4 on 2020-05-02 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20200502_2221'),
        ('property', '0016_flat_owners'),
    ]

    operations = [
    ]
